server:
  port: 8085
spring:
  application:
    name: customer
  cloud:
    gateway:
      routes:
        - id: doctor
          uri: http://localhost:8080/
          predicates:
            - Path=/doctor/**
        - id: patient
          uri: http://localhost:8081/
          predicates:
            - Path=/patient/**

